//This is used for dynomoDB court model
package ac.aut.CloudComputing.bookingsystem.model;

import org.springframework.data.annotation.Id; 
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
// import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;


@Data 
@DynamoDBTable(tableName = "Court")
public class Court  {

    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey  
    private String id;
    
    // The following would create a sort key from the courtName variable for efficient partitioning

    // @Data
    // public static class CourtKey {
    //     @Id
    //     @DynamoDBHashKey(attributeName = "id")
    //     @DynamoDBAutoGeneratedKey  
    //     private String id;

    //     @DynamoDBAttribute(attributeName="court_name")
    //      private String courtName; 
    // }

    @DynamoDBAttribute(attributeName="court_name")
    private String courtName;  

    @DynamoDBAttribute  
    private String image;
    
    @DynamoDBAttribute  
    private String description;
    
    @DynamoDBAttribute  
    private int status;
 
}
