package ac.aut.CloudComputing.bookingsystem.model;
 
import org.springframework.data.annotation.Id;   
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
 


@Data  
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "User")
public class User{

	@Id
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String username;
	@DynamoDBAttribute
	private String email;
	@DynamoDBAttribute
	private String password;
	@DynamoDBAttribute
	private String profileImageS3Key; // Reference to the user's profile image stored in S3
	 

}
