package ac.aut.CloudComputing.bookingsystem.model;

import org.springframework.data.annotation.Id; 
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;


@Data 
@DynamoDBTable(tableName = "Order")
public class Order  {

    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey  
    private String id;
    
    @DynamoDBAttribute
    private String userId; // Reference to the user who placed the order
    
    @DynamoDBAttribute  
    private String description;
    
    @DynamoDBAttribute  
    private double amount;
 
}
